### ISSUE TITLE
Unable to build on Mac M1

### ISSUE THREAD

**Issue by meditant** [esp-rs/esp-idf-sys#288] opened 2024-03-05 10:28 UTC
For 2 days i search on issues and try many thinks but i'm unable to build esp32 ?

Thanks

My PATH def in .profile : 
. "$HOME/.cargo/env"
# RUST-ESP ESP-IDF LLVM
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export PATH="/Users/fr/.rustup/toolchains/esp/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

My .zshenv : 
. "$HOME/.cargo/env"
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
export LIBCLANG_PATH="/Users/fr/.rustup/toolchains/esp/xtensa-esp32-elf-clang/esp-16.0.4-20231113/esp-clang/lib"

% cargo build            
   Compiling esp-idf-sys v0.34.1
The following warnings were emitted during compilation:

warning: esp-idf-sys@0.34.1: (esp-idf-sys) Removed env vars that might affect the ESP IDF C build: `CPPFLAGS=-I/opt/homebrew/opt/llvm/include;LDFLAGS=-L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++`

error: failed to run custom build command for `esp-idf-sys v0.34.1`

Caused by:
  process didn't exit successfully: `/Volumes/Documents/Devel/Rust/test2/target/debug/build/esp-idf-sys-5ad39a82e35dc1cd/build-script-build` (exit status: 101)
  --- stdout
  cargo:warning=(esp-idf-sys) Removed env vars that might affect the ESP IDF C build: `CPPFLAGS=-I/opt/homebrew/opt/llvm/include;LDFLAGS=-L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++`
  cargo:rerun-if-env-changed=ESP_IDF_TOOLS_INSTALL_DIR
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG_DEFAULTS
  cargo:rerun-if-env-changed=MCU
  cargo:rerun-if-env-changed=ESP_IDF_SYS_ROOT_CRATE
  cargo:rerun-if-env-changed=ESP_IDF_VERSION
  cargo:rerun-if-env-changed=ESP_IDF_REPOSITORY
  cargo:rerun-if-env-changed=ESP_IDF_CMAKE_GENERATOR
  cargo:rerun-if-env-changed=IDF_PATH
  cargo:rerun-if-env-changed=EXTRA-COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENT_MANAGER
  IDF_PYTHON_ENV_PATH=/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/python_env/idf5.1_py3.10_env
  ESP_IDF_VERSION=5.1
  PATH=/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/cmake/3.24.0/CMake.app/Contents/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/ninja/1.10.2/:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/python_env/idf5.1_py3.10_env/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/esp-idf/v5.1.3/tools:$PATH
  IDF_DEACTIVATE_FILE_PATH=/var/folders/8t/cnnywgc955d7mmvdnvtzp7ph0000gn/T/tmplhk3k65fidf_36044
  Current system platform: macos-arm64
  Installing tools: xtensa-esp32-elf, cmake, ninja, esp32ulp-elf
  Skipping xtensa-esp32-elf@esp-12.2.0_20230208 (already installed)
  Skipping cmake@3.24.0 (already installed)
  Skipping ninja@1.10.2 (already installed)
  Skipping esp32ulp-elf@2.35_20220830 (already installed)
  IDF_PYTHON_ENV_PATH=/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/python_env/idf5.1_py3.10_env
  ESP_IDF_VERSION=5.1
  PATH=/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/cmake/3.24.0/CMake.app/Contents/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/ninja/1.10.2/:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/python_env/idf5.1_py3.10_env/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/esp-idf/v5.1.3/tools:$PATH
  IDF_DEACTIVATE_FILE_PATH=/var/folders/8t/cnnywgc955d7mmvdnvtzp7ph0000gn/T/tmpiwru2gioidf_36044
  cargo:rerun-if-changed=/Volumes/Documents/Devel/Rust/test2/sdkconfig.defaults
  CMAKE_PREFIX_PATH_xtensa-esp32-espidf = None
  CMAKE_PREFIX_PATH_xtensa_esp32_espidf = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_xtensa-esp32-espidf = None
  CMAKE_xtensa_esp32_espidf = None
  TARGET_CMAKE = None
  CMAKE = None
  running: cd "/Volumes/Documents/Devel/Rust/test2/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-e7fbd4070e43cbc1/out/build" && CMAKE_PREFIX_PATH="" EXTRA_COMPONENT_DIRS="" IDF_COMPONENT_MANAGER="1" IDF_PATH="/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/esp-idf/v5.1.3" IDF_TARGET="esp32" IDF_TOOLS_PATH="/Volumes/Documents/Devel/Rust/test2/.embuild/espressif" PATH="/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/ninja/1.10.2/:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/cmake/3.24.0/CMake.app/Contents/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/python_env/idf5.1_py3.10_env/bin:/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/esp-idf/v5.1.3/tools:/Users/fr/.rustup/toolchains/esp/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin:/Users/fr/miniforge3/bin:/Users/fr/miniforge3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/fr/.cargo/bin" PROJECT_DIR="/Volumes/Documents/Devel/Rust/test2" SDKCONFIG_DEFAULTS="/Volumes/Documents/Devel/Rust/test2/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-e7fbd4070e43cbc1/out/gen-sdkconfig.defaults;/Volumes/Documents/Devel/Rust/test2/sdkconfig.defaults" "cmake" "/Volumes/Documents/Devel/Rust/test2/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-e7fbd4070e43cbc1/out" "-G" "Ninja" "-DCMAKE_TOOLCHAIN_FILE=/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/esp-idf/v5.1.3/tools/cmake/toolchain-esp32.cmake" "-DCMAKE_BUILD_TYPE=" "-DPYTHON=/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/python_env/idf5.1_py3.10_env/bin/python" "-DCMAKE_INSTALL_PREFIX=/Volumes/Documents/Devel/Rust/test2/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-e7fbd4070e43cbc1/out" "-DCMAKE_C_FLAGS= -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections --target=xtensa-esp32-espidf" "-DCMAKE_CXX_FLAGS= -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections --target=xtensa-esp32-espidf" "-DCMAKE_ASM_FLAGS= -mlongcalls -ffunction-sections -fdata-sections --target=xtensa-esp32-espidf"
  -- The C compiler identification is GNU 12.2.0
  -- The CXX compiler identification is GNU 12.2.0
  -- The ASM compiler identification is GNU
  -- Found assembler: /Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - failed
  -- Check for working C compiler: /Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
  -- Check for working C compiler: /Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc - broken
  -- Configuring incomplete, errors occurred!
  See also "/Volumes/Documents/Devel/Rust/test2/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-e7fbd4070e43cbc1/out/build/CMakeFiles/CMakeOutput.log".
  See also "/Volumes/Documents/Devel/Rust/test2/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-e7fbd4070e43cbc1/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  Build configuration: BuildConfig {
      esp_idf_tools_install_dir: None,
      esp_idf_sdkconfig: None,
      esp_idf_sdkconfig_defaults: None,
      mcu: Some(
          "esp32",
      ),
      native: NativeConfig {
          esp_idf_version: Some(
              Tag(
                  "v5.1.3",
              ),
          ),
          esp_idf_repository: None,
          esp_idf_cmake_generator: None,
          idf_path: None,
          extra_components: [],
          esp_idf_components: None,
          esp_idf_component_manager: None,
      },
      esp_idf_sys_root_crate: None,
  }
  Using managed esp-idf repository: RemoteSdk { repo_url: None, git_ref: Tag("v5.1.3") }
  Using esp-idf v5.1.3 at '/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/esp-idf/v5.1.3'
  CMake Error at /Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/cmake/3.24.0/CMake.app/Contents/share/cmake-3.24/Modules/CMakeTestCCompiler.cmake:69 (message):
    The C compiler

      "/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: /Volumes/Documents/Devel/Rust/test2/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-e7fbd4070e43cbc1/out/build/CMakeFiles/CMakeTmp
      
      Run Build Command(s):/Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/ninja/1.10.2/ninja cmTC_4c252 && [1/2] Building C object CMakeFiles/cmTC_4c252.dir/testCCompiler.c.obj
      FAILED: CMakeFiles/cmTC_4c252.dir/testCCompiler.c.obj 
      /Volumes/Documents/Devel/Rust/test2/.embuild/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc   -mlongcalls -Wno-frame-address  -ffunction-sections -fdata-sections --target=xtensa-esp32-espidf -o CMakeFiles/cmTC_4c252.dir/testCCompiler.c.obj -c /Volumes/Documents/Devel/Rust/test2/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-e7fbd4070e43cbc1/out/build/CMakeFiles/CMakeTmp/testCCompiler.c
      xtensa-esp32-elf-gcc: error: unrecognized command-line option '--target=xtensa-esp32-espidf'
      ninja: build stopped: subcommand failed.
      
      

    

    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    /Volumes/Documents/Devel/Rust/test2/.embuild/espressif/esp-idf/v5.1.3/tools/cmake/project.cmake:448 (__project)
    CMakeLists.txt:28 (project)

  thread 'main' panicked at /Users/fr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  stack backtrace:
     0: _rust_begin_unwind
     1: core::panicking::panic_fmt
     2: cmake::fail
               at /Users/fr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
     3: cmake::run
               at /Users/fr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1076:9
     4: cmake::Config::build
               at /Users/fr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:813:13
     5: build_script_build::native::cargo_driver::build
               at ./build/native/cargo_driver.rs:528:5
     6: build_script_build::native::build
               at ./build/native.rs:17:9
     7: build_script_build::main
               at ./build/build.rs:51:24
     8: core::ops::function::FnOnce::call_once
               at /Users/espressif/action-runner/esp-rs/_work/rust-build/rust-build/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by Vollbrecht** [comment] 2024-03-05 10:30
duplicate of https://github.com/esp-rs/esp-idf-sys/issues/287 

There are two solutions presented in the othere issue. Please have a look.

**Closed** 2024-04-09 16:46 UTC
